{% set name = "SDL2_image" %}
{% set version = "2.0.5" %}
{% set sha256 = "bdd5f6e026682f7d7e1be0b6051b209da2f402a2dd8bd1c4bd9c25ad263108d0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn:  {{ name }}-{{ version }}.tar.gz
  url:  https://www.libsdl.org/projects/SDL_image/release/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake  # [win]
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - sdl2 2.0.*
    - jpeg
    - libpng
    - libtiff
    - zlib
    - libwebp

  run:
    - sdl2 2.0.*

test:
  commands:
    - test -f $PREFIX/lib/libSDL2_image.a  # [unix]
    - test -f $PREFIX/lib/libSDL2_image.dylib  # [osx]
    - test -f $PREFIX/lib/libSDL2_image.so  # [linux]
    - test -f $PREFIX/include/SDL2/SDL_image.h  # [unix]
    - if not exist %LIBRARY_LIB%\\SDL2_image.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\SDL2_image.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\\SDL2\\SDL_image.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\\SDL2\\miniz.h exit 1  # [win]

about:
  home: https://www.libsdl.org/projects/SDL_image/
  license: ZLIB
  license_file: COPYING.txt
  summary: "Library for loading images as SDL surfaces and textures"
  description: |
    Simple DirectMedia Layer is a cross-platform development library designed to
    provide low level access to audio, keyboard, mouse, joystick, and graphics
    hardware via OpenGL and Direct3D.
  doc_url: https://www.libsdl.org/projects/SDL_image/docs/index.html
  dev_url: http://hg.libsdl.org/SDL_image/

extra:
  recipe-maintainers:
    - dschreij
