{% set version = "2.6.0" %}

package:
  name: sdl2_image
  version: {{ version }}

source:
  url: https://github.com/libsdl-org/SDL_image/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: fb61d96446cdb1668f837dd7ba1d22d6631755d5dda86580a1cb5aefa3e62278

build:
  number: 0

requirements:
  build:
    - cmake  # [win]
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - sdl2 2.0.*
    - jpeg
    - libpng
    - libtiff
    - zlib
    - libwebp

  run:
    - sdl2 2.0.*

test:
  commands:
    - test -f $PREFIX/lib/libSDL2_image.a  # [unix]
    - test -f $PREFIX/lib/libSDL2_image.dylib  # [osx]
    - test -f $PREFIX/lib/libSDL2_image.so  # [linux]
    - test -f $PREFIX/include/SDL2/SDL_image.h  # [unix]
    - if not exist %LIBRARY_LIB%\\SDL2_image.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\SDL2_image.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\\SDL2\\SDL_image.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\\SDL2\\miniz.h exit 1  # [win]

about:
  home: https://www.libsdl.org/projects/SDL_image/
  license: Zlib
  license_file: LICENSE.txt
  summary: "Library for loading images as SDL surfaces and textures"
  description: |
    Simple DirectMedia Layer is a cross-platform development library designed to
    provide low level access to audio, keyboard, mouse, joystick, and graphics
    hardware via OpenGL and Direct3D.
  doc_url: https://wiki.libsdl.org/SDL_image
  dev_url: https://github.com/libsdl-org/SDL_image

extra:
  recipe-maintainers:
    - dschreij
    - a-hurst
