{% set version = "3.2.2" %}

package:
  name: sdl3_image
  version: {{ version }}

source:
  url: https://github.com/libsdl-org/SDL_image/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: 29f5d94f7f0769655696feb615849d9ad610bab548ceab6a46c9511340be3d6e
  patches:
    - patches/0001-look-for-conda-forge-variant-of-libwebp.patch                # [win]
    - patches/0002-BLD-Use-CMake-artifacts-instead-of-custom-findwebp.patch     # [win]

build:
  number: 0
  run_exports:
    # see https://abi-laboratory.pro/tracker/timeline/sdl_image
    - {{ pin_subpackage("sdl3_image", max_pin="x") }}

requirements:
  build:
    - cmake
    - ninja
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - sdl3
    - libjpeg-turbo
    - libavif
    # not yet in conda-forge
    # - libjxl
    - libpng
    - libtiff
    - libwebp-base
    - zlib

test:
  commands:
    # shared libraries
    - test -f $PREFIX/lib/libSDL3_image.dylib               # [osx]
    - test -f $PREFIX/lib/libSDL3_image.so                  # [linux]
    - if not exist %LIBRARY_LIB%\SDL3_image.lib exit 1      # [win]
    - if not exist %LIBRARY_BIN%\SDL3_image.dll exit 1      # [win]

    # absence of static libraries
    - test ! -f $PREFIX/lib/libSDL3_image.a                 # [unix]

    # headers
    - test -f $PREFIX/include/SDL3_image/SDL_image.h            # [unix]
    - if not exist %LIBRARY_INC%\SDL3_image\SDL_image.h exit 1  # [win]

about:
  home: https://www.libsdl.org/projects/SDL_image/
  license: Zlib
  license_file: LICENSE.txt
  summary: Library for loading images as SDL surfaces and textures
  description: |
    Simple DirectMedia Layer is a cross-platform development library designed to
    provide low level access to audio, keyboard, mouse, joystick, and graphics
    hardware via OpenGL and Direct3D.
  doc_url: https://wiki.libsdl.org/SDL_image
  dev_url: https://github.com/libsdl-org/SDL_image

extra:
  recipe-maintainers:
    - dschreij
    - a-hurst
    - h-vetinari
