appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YPamLPeUUfDNaOnxGTMYKqaGsf0JWVEJbPxeBji0wS4W50CRUOc3R/YL5NjsmOjKQsUFuumyK2a7DSVBRmfG4dMvt+yBAoDReeVCZzU1RUhey56Zqh9H66osEvaw8eCY0+iyi+lH18HWkiPJ2fT0rVvT5GjLL/cA+NPKA8B7gUmojJJ3AkS1ezQIYlm0vHgENJJeq0t61UETcxba/h4AU4IeaN51QKcGwzMMmMjCsrUlrwyisIhPWfbY/XL4PpcNMKiO+Dw7IXRlqHbiMnICBMj77XMkG7yaScrdabcONAQ070oZdAWk2mXOmScdlWRitIpSI4Dy8VHSpqmdY4iCIDW0uHTjvjRdwKw2jejVmQouoraLOkPLaLhCCRAmosD90c+1Wfby3/nUMEfqW9mNjYxBzTzItHv5RaVelakdwRH+T8u3ItOunR8OE2JtS0ULdaTqjlu9rRR73Ez82ES65EwGV15jPeHMVHD8tjf9i4o1nMDhw8D7C1nRAN3O9HLNR0cTZETCDuyE7DMlJdpaH2yyj0FqZ652lvh2eB4Ht5EoIad6BjHSy7UCBF4/CN3JdFORp5d2f1SEtb/wnEJo1w4xU1uhwyM5pem6Tp2u/3SJ5CkefPoKCrJq1OE6R9Z7uQn+Sb+eNRvz7cnx/JKijD4tOyFK8YH3CztZNpiCJcU=}
